
.TH aclients 1 "September 2014" "aclients(1)" "Ham Radio Applications"

.SH NAME
\fBaclients\fR \- Compare APRS clients

.SH SYNOPSIS

\fBaclients\fR \fBport=type\fR\ [\fBport=type\fR [\fBport=type\fR ...]]

.SH DESCRIPTION

aclients connects to up to 6 TNC applications at the same time and prints the packets in columns. From a distance, it’s easy to see the general trend of how they compare. Periodically total numbers of packets received are printed.

.SH OPTIONS

.PP
port
.RS 4
Either a local TCP port number or device path for a serial interface (e.g. /dev/ttySX).
.RE
.PP
type
.RS 4
One of the following:
.RS 2
AWGPE - AWG Packet Engine
.br
UZ7HO - UZ7HO Soundmodem
.br
DireWolf - Dire Wolf
.br
KPC3+ - Kantronics KPC-3+
.br
D710A - Kenwood TM-D710A
.RE
.RE

.SH "AUTHORS"

Dire Wolf is Copyright \(co 2011-2014 John Langner WB2OSZ\&.

.SH "COPYRIGHT"
.br
This manual page is Copyright \(co 2014 Iain R. Learmonth\&.
.br
.PP
This manual page was written for the Debian system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL-2\&.

.SH "SEE ALSO"

direwolf(1)

.sp

