
.TH text2tt 1 "September 2014" "text2tt(1)" "Ham Radio Applications"

.SH NAME
\fBtext2tt\fR \- Convert text to APRStt

.SH SYNOPSIS

\fBtext2tt\fR \fBtext\fR\

.SH OPTIONS

Simply pass the text to convert as the command line argument.

.SH "AUTHORS"

Dire Wolf is Copyright \(co 2011-2014 John Langner WB2OSZ\&.

.SH "COPYRIGHT"
.br
This manual page is Copyright \(co 2014 Iain R. Learmonth\&.
.br
.PP
This manual page was written for the Debian system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL-2\&.

.SH "SEE ALSO"

direwolf(1), tt2text(1)

.sp

