
.TH tt2text 1 "September 2014" "tt2text(1)" "Ham Radio Applications"

.SH NAME
\fBtt2text\fR \- Convert APRStt to text

.SH SYNOPSIS

\fBtt2text\fR \fBtext\fR\

.SH OPTIONS

Simply pass the keypresses to convert as the command line argument.

.SH "AUTHORS"

Dire Wolf is Copyright \(co 2011-2014 John Langner WB2OSZ\&.

.SH "COPYRIGHT"
.br
This manual page is Copyright \(co 2014 Iain R. Learmonth\&.
.br
.PP
This manual page was written for the Debian system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL-2\&.

.SH "SEE ALSO"

direwolf(1), text2tt(1)

.sp

