
.TH utm2ll 1 "September 2014" "utm2ll(1)" "Ham Radio Applications"

.SH NAME
\fButm2ll\fR \- UTM to Latitude / Longitude conversion

.SH SYNOPSIS

\fButm2ll\fR \fBzone\fR \fBeasting\fR \fBnorthing\fR

.SH OPTIONS

.PP
zone \- UTM zone 1 thru 60 with optional latitudinal band
.PP
easting \- x coordinate in meters
.PP
northing \- y coordinate in meters

.SH "AUTHORS"

Dire Wolf is Copyright \(co 2011-2014 John Langner WB2OSZ\&.

.SH "COPYRIGHT"
.br
This manual page is Copyright \(co 2014 Iain R. Learmonth\&.
.br
.PP
This manual page was written for the Debian system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL-2\&.

.SH "SEE ALSO"

direwolf(1), ll2utm(1)

.sp

